// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrdersManager.Database;

#nullable disable

namespace OrdersManager.Database.Migrations
{
    [DbContext(typeof(OrdersManagerDbContext))]
<<<<<<<< HEAD:OrdersManager.Database/Migrations/20220901094019_InitDatabase.Designer.cs
    [Migration("20220901094019_InitDatabase")]
    partial class InitDatabase
========
    [Migration("20220906103722_InitDb")]
    partial class InitDb
>>>>>>>> feature/add-fluent-API:OrdersManager.Database/Migrations/20220906103722_InitDb.Designer.cs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrdersManager.Domain.Models.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Mark")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrderId")
                        .HasMaxLength(36)
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("OrdersManager.Domain.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasMaxLength(36)
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScheduleId")
                        .HasMaxLength(36)
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OrdersManager.Domain.Models.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MasterId")
                        .HasMaxLength(36)
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceId")
                        .HasMaxLength(36)
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("OrdersManager.Domain.Models.Feedback", b =>
                {
                    b.HasOne("OrdersManager.Domain.Models.Order", "Order")
<<<<<<<< HEAD:OrdersManager.Database/Migrations/20220901094019_InitDatabase.Designer.cs
                        .WithMany()
========
                        .WithMany("Feedbacks")
>>>>>>>> feature/add-fluent-API:OrdersManager.Database/Migrations/20220906103722_InitDb.Designer.cs
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });
<<<<<<<< HEAD:OrdersManager.Database/Migrations/20220901094019_InitDatabase.Designer.cs
========

            modelBuilder.Entity("OrdersManager.Domain.Models.Order", b =>
                {
                    b.HasOne("OrdersManager.Domain.Models.Schedule", "Schedule")
                        .WithOne("Order")
                        .HasForeignKey("OrdersManager.Domain.Models.Order", "ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("OrdersManager.Domain.Models.Order", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("OrdersManager.Domain.Models.Schedule", b =>
                {
                    b.Navigation("Order")
                        .IsRequired();
                });
>>>>>>>> feature/add-fluent-API:OrdersManager.Database/Migrations/20220906103722_InitDb.Designer.cs
#pragma warning restore 612, 618
        }
    }
}
